name: Build and Package
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
      
      - name: Setup Gradle
        uses: gradle/setup-gradle@v1
        with:
          gradle-version: '8.1'
      
      - name: Compile Kotlin wrapper
        run: ./gradlew clean shadowJar
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: |
            wrappers/Javascript/harbor.js
            wrappers/Python/harbor.py
            build/libs/harbor-1.0.0-all.jar
            harbor.sh